- symbol: "WIPRO"
  company: "Wipro Limited"
  sector: "IT"
- symbol: "TCS"
  company: "Tata Consultancy Services"
  sector: "IT"
- symbol: "INFY"
  company: "Infosys Limited"
  sector: "IT"
- symbol: "HCLTECH"
  company: "HCL Technologies"
  sector: "IT"
- symbol: "TECHM"
  company: "Tech Mahindra"
  sector: "IT"
- symbol: "HDFCBANK"
  company: "HDFC Bank"
  sector: "Banking"
- symbol: "SBIN"
  company: "State Bank of India"
  sector: "Banking"
- symbol: "ICICIBANK"
  company: "ICICI Bank"
  sector: "Banking"
- symbol: "KOTAKBANK"
  company: "Kotak Mahindra Bank"
  sector: "Banking"
- symbol: "AXISBANK"
  company: "Axis Bank"
  sector: "Banking"
- symbol: "BANKBARODA"
  company: "Bank of Baroda"
  sector: "Banking"
- symbol: "ITC"
  company: "ITC Limited"
  sector: "FMCG"
- symbol: "HINDUNILVR"
  company: "Hindustan Unilever"
  sector: "FMCG"
- symbol: "NESTLEIND"
  company: "Nestle India"
  sector: "FMCG"
- symbol: "BRITANNIA"
  company: "Britannia Industries"
  sector: "FMCG"
- symbol: "TMPV"
  company: "Tata Motors Passenger Vehicles"
  sector: "Auto"
- symbol: "MARUTI"
  company: "Maruti Suzuki"
  sector: "Auto"
- symbol: "BAJAJ-AUTO"
  company: "Bajaj Auto"
  sector: "Auto"
- symbol: "EICHERMOT"
  company: "Eicher Motors"
  sector: "Auto"
- symbol: "RELIANCE"
  company: "Reliance Industries"
  sector: "Energy"
- symbol: "ONGC.NS"
  company: "Oil and Natural Gas Corporation"
  sector: "Energy"
- symbol: "BPCL"
  company: "Bharat Petroleum"
  sector: "Energy"
- symbol: "NTPC"
  company: "NTPC Limited"
  sector: "Energy"
- symbol: "BAJFINANCE"
  company: "Bajaj Finance"
  sector: "Finance"
- symbol: "BAJAJFINSV"
  company: "Bajaj Finserv"
  sector: "Finance"
- symbol: "HDFCLIFE"
  company: "HDFC Life Insurance"
  sector: "Finance"
- symbol: "SUNPHARMA"
  company: "Sun Pharmaceutical"
  sector: "Pharma"
- symbol: "DRREDDY"
  company: "Dr Reddys Laboratories"
  sector: "Pharma"
- symbol: "CIPLA"
  company: "Cipla Limited"
  sector: "Pharma"
- symbol: "LT"
  company: "Larsen and Toubro"
  sector: "Infra"
- symbol: "ULTRACEMCO"
  company: "UltraTech Cement"
  sector: "Infra"
- symbol: "TATASTEEL"
  company: "Tata Steel"
  sector: "Metals"
- symbol: "JSWSTEEL"
  company: "JSW Steel"
  sector: "Metals"
- symbol: "ASIANPAINT"
  company: "Asian Paints"
  sector: "Consumer"
- symbol: "TITAN"
  company: "Titan Company"
  sector: "Consumer"
